foo: (( defer )) # should generate an error